services:
    app:
      build:
        context: ..
        dockerfile: .devcontainer/Dockerfile

      volumes:
        - ../..:/workspaces/:cached

      command: sleep infinity

    valkey:
      image: valkey/valkey

    vectordb:
      image: qdrant/qdrant
      ports:
        - 6333:6333


